// Copyright 2020-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_FROG_memory_initialization_control.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-07-08
*IP Status*::
    No known IP claims.
*Contributors*::
  - Hans-Kristian Arntzen, Valve
  - Friedrich Vock, Valve

=== Description

This extension allows applications to control the initial state of memory
after allocating a fresh slink:VkDeviceMemory object.
This can be very useful for API layering, since the layered API may
have stronger guarantees about the initial state of memory,
which would need to be emulated rather than relying on the implementation to provide the functionality in a more efficient way.

When allocating a new memory object (i.e. not imported external memory),
slink:VkMemoryInitializationCreateInfoFROG can be
passed in the pname:pNext chain of slink:VkMemoryAllocateInfo to control which behavior
is desired. ename:VK_MEMORY_INITIALIZATION_MODE_DONT_CARE_FROG is intended
for scenarios where memory does not have to be initialized and either application will take care of it,
or uninitialized memory is acceptable.
This mode does not allow applications to bypass security mechanisms defined by the platform,
but for situations where memory is recycled within a process, applications may: observe
uninitialized memory.

Implementations may: also provide information in slink:VkPhysicalDeviceMemoryInitializationControlPropertiesFROG
asking that applications perform their own initialization rather than rely on
the implementation to perform it if high throughput is desired.
Some implementations may perform internal memory initialization with a lower
throughput than expected as a way to not disrupt performance of other device
work.

include::{generated}/interfaces/VK_FROG_memory_initialization_control.adoc[]

=== Version History

  * Revision 1, 2023-07-07 (Hans-Kristian Arntzen)
  ** Initial specification
